---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    app.openshift.io/runtime: nodejs
  labels:
    app: nodejs-pipeline
    app.kubernetes.io/instance: nodejs-pipeline-instance
    app.kubernetes.io/name: nodejs-pipeline
  name: nodejs-pipeline
spec:
  params:
    - name: source-repo
      type: string
      description: Source code repository
  workspaces:
    - name: pipeline-shared-data
      description: |
        This workspace stores the cloned repository and is a
  tasks:
    - name: clone-repository
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: "$(params.source-repo)"
      workspaces:
        - name: output
          workspace: pipeline-shared-data
